[package]
name = "dbr-impex"
version = "0.1.0"
edition = "2024"

[lib]
name = "dbr_impex"
path = "src/lib.rs"

[[bin]]
name = "dbr-impex"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
reqwest = { version = "0.13.3", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tempdir = "0.3.7"
thiserror = "2.0.18"

[dev-dependencies]
httpmock = "0.8.3"
